# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restraunt', '0002_rlist_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rlist',
            new_name='restlist',
        ),
    ]
