# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restraunt', '0004_remove_restlist_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='restlist',
            name='int_field',
            field=models.CommaSeparatedIntegerField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='restlist',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
