# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restraunt', '0005_auto_20171008_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restlist',
            name='int_field',
        ),
    ]
